# Generated by Django 3.2 on 2023-10-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userloginn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
