# Generated by Django 3.2 on 2023-10-27 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_userapp', '0002_userloginn'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_login',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom_userapp.userloginn'),
        ),
    ]
