# Generated by Django 3.2 on 2023-10-31 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_adminapp', '0012_auto_20231031_1207'),
        ('ecom_userapp', '0004_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom_adminapp.product'),
        ),
    ]
