# Generated by Django 3.2 on 2023-11-03 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_adminapp', '0012_auto_20231031_1207'),
        ('ecom_userapp', '0006_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=100)),
                ('amount_paid', models.CharField(blank=True, max_length=100, null=True)),
                ('order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Paid', max_length=10)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom_userapp.address')),
                ('selected_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom_adminapp.size')),
                ('user_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_userapp.userloginn')),
            ],
        ),
    ]
