# Generated by Django 3.2 on 2023-10-03 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_adminapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adminsign',
        ),
    ]
