# Generated by Django 3.2 on 2023-10-06 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_adminapp', '0003_addcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=225)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_adminapp.addcategory')),
            ],
        ),
    ]
