# Generated by Django 3.2 on 2023-10-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_adminapp', '0008_color_productcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
